(define decr-ints
    (lambda (n)
        ((loop (lambda (i)
            (if (zero?)
                '()
                (cons i (loop (1- i)))
            )
        )))
        (loop n)
    )
)

(define int25 (decr-ints 25))
(define int50 (decr-ints 50))
(define int100 (decr-ints 100))
(define v-int25 (list->vector int25))
(define v-int50 (list->vector int50))
(define v-int100 (list->vector int100))
