(load "ch12/ex12-33.scm")

(define manhattan-origin-maker
    (lambda ()
        (let ((p (cartesian-origin-maker)))
            (lambda message
                (let ((self (car message)) (msg (cdr message)))
                    (case (1st msg)
                        ((type) "Manhattan point")
                        ((distance)
                            (let ((xy-ls (self self 'current-coordinates)))
                                (apply + xy-ls)
                            )
                        )
                        (else (delegate p message))
                    )
                )
            )
        )
    )
)
