(define mystery
    (lambda (pos-int)
        (letrec ((helper (lambda (n count)
            (cond
                ((= n 1)
                    (newline)
                    (display "It took ")
                    (display count)
                    (display " steps to get to 1.")
                )
                ((even? n)
                    (newline)
                    (display count)
                    (display ". We divide ")
                    (display n)
                    (display " by 2.")
                    (newline)
                    (helper (/ n 2) (add1 count))
                )
                (else
                    (newline)
                    (display count)
                    (display ". We multiply ")
                    (display n)
                    (display " by 3 and add 1.")
                    (helper (+ (* n 3) 1) (1+ count))
                )
            )
        )))

        (helper pos-int 0)

        )
    )
)
